# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(help_text='Format: DD/MM/YYYY')),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('home_address', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter in international number format', max_length=128)),
                ('country_of_residence', django_countries.fields.CountryField(max_length=2)),
                ('occupation', models.CharField(max_length=50)),
                ('postal_address', models.CharField(max_length=50)),
                ('programme_of_study', models.CharField(max_length=100)),
                ('name_of_institution', models.CharField(max_length=100)),
                ('name_of_Guardian', models.CharField(max_length=100, verbose_name='Name of Guardian/Emergency Contact Person')),
                ('relationship_with_applicant', models.CharField(max_length=50)),
                ('contact_number_of_guardian', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter in international number format', max_length=128, verbose_name='Contact Number of Guardian')),
                ('hostel_required', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='Do you require Accomodation?')),
                ('choice_of_accomodation', models.CharField(blank=True, choices=[('2P', 'Two Persons'), ('3P', 'Three Persons'), ('4P', 'Four Persons')], max_length=2)),
                ('special_need', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='Do you have a physical/Dietary Need?')),
                ('need', models.CharField(blank=True, max_length=50, verbose_name='If yes, specify')),
                ('shirt_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], max_length=3, verbose_name='Size of Shirt')),
                ('visa_required', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='Do you require visa to enter Nigeria?')),
                ('passport_number', models.CharField(blank=True, help_text='If yes, please state your passport number', max_length=100)),
                ('visa_exp_date', models.DateField(blank=True, help_text='Format: DD/MM/YYYY', verbose_name='Visa Expiry Date')),
                ('category', models.CharField(choices=[('DEL', 'Delegate'), ('OFF', 'Official'), ('OBS', 'Observer')], help_text='Select your category', max_length=3)),
                ('country_choice_one', django_countries.fields.CountryField(help_text='First most preferred', max_length=2, verbose_name='Country of Choice')),
                ('country_choice_two', django_countries.fields.CountryField(help_text='Second most preferred', max_length=2, verbose_name='Country of Choice')),
                ('country_choice_three', django_countries.fields.CountryField(help_text='Third most preferred', max_length=2, verbose_name='Country of Choice')),
                ('committee_choice', models.CharField(max_length=50, verbose_name='Committee of Choice')),
                ('previous_experience', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], help_text='Do you have any previous Model UN conference experience?', max_length=1)),
                ('previous_role', models.CharField(blank=True, choices=[('DEL', 'Delegate'), ('OFF', 'Official'), ('OBS', 'Observer')], help_text='If yes, please what was your role?', max_length=3, verbose_name='Role')),
                ('previous_committee', models.CharField(blank=True, help_text='Which committee did you participate either as a delegate/official?', max_length=50, verbose_name='Committee')),
                ('point_of_contact', models.CharField(choices=[('S', 'Social Media'), ('W', 'Website'), ('OBS', 'Observer'), ('FOR', 'Friend / Relative'), ('AMB', 'Campus Ambassador'), ('OTH', 'Others')], help_text='How did you hear about IFE Model UN conference 2018?', max_length=3)),
            ],
        ),
    ]
