# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationForm',
            new_name='Delegate',
        ),
    ]
