# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='visa_exp_date',
            field=models.DateField(blank=True, help_text='Format: DD/MM/YYYY', null=True, verbose_name='Visa Expiry Date'),
        ),
    ]
