# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_auto_20180228_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Please enter your referral code? (If referred by a Campus Ambassador )', max_length=50),
        ),
    ]
