# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_applicant_referral_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
