# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField(help_text=b'Format: DD/MM/YYYY', verbose_name=b'Date of Birth')),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[(b'F', b'Female'), (b'M', b'Male')], max_length=1)),
                ('home_address', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text=b'Enter in international number format', max_length=128)),
                ('country_of_residence', django_countries.fields.CountryField(max_length=2)),
                ('occupation', models.CharField(max_length=50)),
                ('postal_address', models.CharField(max_length=50)),
                ('programme_of_study', models.CharField(max_length=100)),
                ('name_of_institution', models.CharField(max_length=100)),
                ('name_of_Guardian', models.CharField(max_length=100, verbose_name=b'Name of Guardian/Emergency Contact Person')),
                ('relationship_with_applicant', models.CharField(max_length=50)),
                ('contact_number_of_guardian', phonenumber_field.modelfields.PhoneNumberField(help_text=b'Enter in international number format', max_length=128, verbose_name=b'Contact Number of Guardian')),
                ('hostel_required', models.CharField(choices=[(b'Y', b'Yes'), (b'N', b'No')], max_length=1, verbose_name=b'Do you require Accomodation?')),
                ('choice_of_accomodation', models.CharField(blank=True, choices=[(b'2P', b'Two Persons'), (b'3P', b'Three Persons'), (b'4P', b'Four Persons')], max_length=2)),
                ('special_need', models.CharField(choices=[(b'Y', b'Yes'), (b'N', b'No')], max_length=1, verbose_name=b'Do you have a physical/Dietary Need?')),
                ('need', models.CharField(blank=True, max_length=50, verbose_name=b'If yes, specify')),
                ('shirt_size', models.CharField(choices=[(b'S', b'Small'), (b'M', b'Medium'), (b'L', b'Large'), (b'XL', b'Extra Large'), (b'XXL', b'Extra Extra Large')], max_length=3, verbose_name=b'Size of Shirt')),
                ('visa_required', models.CharField(choices=[(b'Y', b'Yes'), (b'N', b'No')], max_length=1, verbose_name=b'Do you require visa to enter Nigeria?')),
                ('passport_number', models.CharField(blank=True, help_text=b'If yes, please state your passport number', max_length=100)),
                ('visa_exp_date', models.DateField(blank=True, help_text=b'Format: DD/MM/YYYY', null=True, verbose_name=b'Visa Expiry Date')),
                ('category', models.CharField(choices=[(b'DEL', b'Delegate'), (b'OFF', b'Official'), (b'OBS', b'Observer')], help_text=b'Select your category', max_length=3)),
                ('country_choice_one', django_countries.fields.CountryField(help_text=b'First most preferred', max_length=2, verbose_name=b'Country of Choice')),
                ('country_choice_two', django_countries.fields.CountryField(help_text=b'Second most preferred', max_length=2, verbose_name=b'Country of Choice')),
                ('country_choice_three', django_countries.fields.CountryField(help_text=b'Third most preferred', max_length=2, verbose_name=b'Country of Choice')),
                ('committee_choice', models.CharField(max_length=50, verbose_name=b'Committee of Choice')),
                ('previous_experience', models.CharField(choices=[(b'Y', b'Yes'), (b'N', b'No')], help_text=b'Do you have any previous Model UN conference experience?', max_length=1)),
                ('previous_role', models.CharField(blank=True, choices=[(b'DEL', b'Delegate'), (b'OFF', b'Official'), (b'OBS', b'Observer')], help_text=b'If yes, please what was your role?', max_length=3, verbose_name=b'Role')),
                ('previous_committee', models.CharField(blank=True, help_text=b'Which committee did you participate either as a delegate/official?', max_length=50, verbose_name=b'Committee')),
                ('point_of_contact', models.CharField(choices=[(b'S', b'Social Media'), (b'W', b'Website'), (b'OBS', b'Observer'), (b'FOR', b'Friend / Relative'), (b'AMB', b'Campus Ambassador'), (b'OTH', b'Others')], help_text=b'How did you hear about IFE Model UN conference 2018?', max_length=3)),
                ('referral_code', models.CharField(blank=True, help_text=b'Please enter your referral code? (If referred by a Campus Ambassador )', max_length=50)),
            ],
        ),
    ]
