# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20180307_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='committee_choice',
            field=models.CharField(choices=[(b'UNSC', b'United Nations Security Council'), (b'DISEC', b'GA1 DISEC'), (b'UNCHR', b'United Nations Commission for Human Right'), (b'ECOFIN', b'GA3 ECOFIN'), (b'IOC', b'International Olympic Committee'), (b'WHO', b'World Health Organization'), (b'UNESCO', b'United Nations Educational, Scientific and Cultural Organization')], max_length=8, verbose_name=b'Committee of Choice'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='previous_committee',
            field=models.CharField(blank=True, choices=[(b'UNSC', b'United Nations Security Council'), (b'DISEC', b'GA1 DISEC'), (b'UNCHR', b'United Nations Commission for Human Right'), (b'ECOFIN', b'GA3 ECOFIN'), (b'IOC', b'International Olympic Committee'), (b'WHO', b'World Health Organization'), (b'UNESCO', b'United Nations Educational, Scientific and Cultural Organization')], help_text=b'Which committee did you participate either as a delegate/official?', max_length=50, verbose_name=b'Committee'),
        ),
    ]
