# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20180307_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='visa_exp_date',
        ),
        migrations.AddField(
            model_name='applicant',
            name='passport_exp_date',
            field=models.DateField(blank=True, help_text=b'Format: DD/MM/YYYY', null=True, verbose_name=b'Passport Expiry Date'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='category',
            field=models.CharField(choices=[(b'DEL', b'Delegate'), (b'OFF', b'Official'), (b'OBS', b'Observer'), (b'AMB', b'Campus Ambassador')], help_text=b'Select your category', max_length=3, verbose_name=b'Registration Category'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='previous_committee',
            field=models.CharField(blank=True, help_text=b'Which committee did you participate either as a delegate/official?', max_length=70, verbose_name=b'Committee'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='previous_role',
            field=models.CharField(blank=True, choices=[(b'DEL', b'Delegate'), (b'OFF', b'Official'), (b'OBS', b'Observer'), (b'AMB', b'Campus Ambassador')], help_text=b'If yes, please what was your role?', max_length=3, verbose_name=b'Role'),
        ),
    ]
