# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20180311_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='postal_address',
        ),
    ]
