# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-21 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_remove_applicant_postal_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='committee_choice',
            field=models.CharField(choices=[(b'UNSC', b'United Nations Security Council'), (b'DISEC', b'GA1 DISEC'), (b'UNCHR', b'United Nations Commission for Human Right'), (b'ECOFIN', b'GA3 ECOFIN'), (b'IOC', b'International Olympic Committee'), (b'WHO', b'World Health Organization'), (b'UNESCO', b'United Nations Educational, Scientific and Cultural Organization')], help_text=b'Kindly check the "Committees" page for details', max_length=8, verbose_name=b'Committee of Choice'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='previous_committee',
            field=models.CharField(blank=True, help_text=b'Which committee did you participate either as a delegate/official?', max_length=70, verbose_name=b'Previous Committee'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='previous_experience',
            field=models.CharField(choices=[(b'Y', b'Yes'), (b'N', b'No')], help_text=b'Do you have any previous Model UN conference experience?', max_length=1, verbose_name=b'Previous MUN Experience'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='previous_role',
            field=models.CharField(blank=True, choices=[(b'DEL', b'Delegate'), (b'OFF', b'Official'), (b'OBS', b'Observer')], help_text=b'If yes, please what was your role?', max_length=3, verbose_name=b'Previous Role'),
        ),
    ]
