# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-16 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20180311_0747'),
        ('registration', '0006_auto_20180421_1749'),
    ]

    operations = [
    ]
