# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-24 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_merge_20180516_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
