# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-24 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20180524_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='amount_paid',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='applicant',
            name='package',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='applicant',
            name='payment_type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
