# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-24 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20180524_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='package',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='payment_type',
        ),
    ]
