# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-27 18:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180425_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_summary',
            field=models.CharField(default='Urban public institutions life-saving women and children Rockefeller combat malaria honesty. Sustainability foster immunize treatment.', max_length=200, validators=[django.core.validators.MinValueValidator(140)]),
            preserve_default=False,
        ),
    ]
