# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 21:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180218_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 21, 15, 32, 871196, tzinfo=utc)),
        ),
    ]
