# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 02:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180228_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 28, 2, 52, 3, 289276, tzinfo=utc)),
        ),
    ]
